# Generated by Django 2.2.5 on 2019-09-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_auto_20190924_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_id'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
